### ISSUE TITLE
parallel the null distribution computation

### ISSUE THREAD

**Issue by ccshao** [ncchung/jackstraw#1]
When apply jackstraw on a larger matrix, e.g., a size of 20000 * 1000 matrix, computing the null distribution takes lots of time. Could this step be run in parallel?

**Comment by ncchung** [comment]
Hi,

Thanks for a great question. Computing the jackstraw null statistics is "embarrassing parallel". You can (1) run the jackstraw algorithm multiple instances, (2) collect null statistics in `null.stat`, and (3) use `empPvals` to compute p-values.  

However it is not an elegant solution and certainly inefficient in memory usage. Taking advantages of multicores is a high priority for me.

Please feel free to tell me more about your specific problem, and I'm happy to help.

**Comment by ccshao** [comment]
Thanks, I am playing with single-cell data, usually in the scale of 2k cells. It takes too long to run jackstraw with datasets. Interestingly, there is an R package Seurat implementing the parallelization
version of jackstraw independently(?).

**Comment by ncchung** [comment]
Yes, the Seurat package has an implementation of the jackstraw method, focusing on identifying a number of significant principal components. It's a great package for scRNAseq data. On the other hand, the jackstraw package is more flexible and has diverse use cases. 

Please subscribe to this repository and you will be notified about the new updates!
