### ISSUE TITLE
installing jackstraw from CRAN fails due to missing packages

### ISSUE THREAD

**Issue by idc9** [ncchung/jackstraw#2]
# problem
When I install jackstraw from CRAN it does not work because it fails to install two packages: `qvalue` and `lfa` e.g.
```
install.packages('jackstraw')
> library(jackstraw)
Error: package or namespace load failed for ‘jackstraw’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘lfa’
```

# solution

After installing these two packages I can load jackstraw
```R
# install.packages("devtools")
library("devtools")
install_github("Storeylab/lfa")   # see note for OS X users on lfa's github page
install_github("jdstorey/qvalue")
```

You might consider having these installed automatically or making them optional. Adding this as a note on the readme would also be helpful.

# system details

```
> R.Version() 
$platform
[1] "x86_64-apple-darwin15.6.0"

$arch
[1] "x86_64"

$os
[1] "darwin15.6.0"

$system
[1] "x86_64, darwin15.6.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "4.3"

$year
[1] "2017"

$month
[1] "11"

$day
[1] "30"

$`svn rev`
[1] "73796"

$language
[1] "R"

$version.string
[1] "R version 3.4.3 (2017-11-30)"

$nickname
[1] "Kite-Eating Tree"
```

**Comment by ncchung** [comment]
Thanks for raising this issue.  I've updated the [README](https://github.com/ncchung/jackstraw/blob/master/README.md) file to reflect your suggestion.

FYI, I had included `biocViews:` in the description file to automatically search and install the bioconductor packages (https://github.com/r-lib/devtools/issues/700#issuecomment-235127291). But it seems that trick doesn't work always.

**Comment by kohlkopf** [comment]
I've just had the same issue. Installing the packages that idc9 installs allows me to load jackstraw.
