### ISSUE TITLE
Is PC argument actually r1?  

### ISSUE THREAD

**Issue by djbajic** [ncchung/jackstraw#3]
Hi, 

I am working with a gene expression dataset where I am interested in knowing which genes contribute significantly to any given mode (or PC) out of 15 or so significant. The "details" section mentions the `PC` argument (which is what I need, I think), but the function actually does not accept such argument. I suspect that the `PC` argument was renamed to `r1`, could you please confirm this?

Thanks a lot!

**Comment by ncchung** [comment]
Hi @djbajic 

Yes, you are correct. I'll update the help files asap.
